# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Allows all origins
        allow_headers: ['*']  # Allows all headers
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':  # Apply this CORS configuration to all API routes
            allow_origin: ['*']  # Allows all origins for API routes
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
            expose_headers: []
