version: '3.1'

services:
  # PostgreSQL service
  db:
    image: postgres:latest
    container_name: food_ordering_db
    environment:
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: burger
      POSTGRES_DB: food_ordering_dbdocker-compose up -d

    ports:
      - "5432:5432"  # Expose PostgreSQL to the host on port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data across container restarts

volumes:
  pgdata:  # This volume stores the PostgreSQL data
